nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://talent-finder-4staffing.vercel.app', '%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['https://talent-finder-4staffing.vercel.app', '%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE']
            max_age: 3600